# Generated by Django 4.0.2 on 2022-03-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gaflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
    ]
