# Generated by Django 4.0.2 on 2022-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaflix', '0002_director_person_category_title_movie_actord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actord',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, to='Gaflix.Actor'),
        ),
    ]
